title: HVboom Knowledge Base
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

author: HVboom
description: Personal AI + DevOps Workspace Documentation
url: "https://home.hvboom.biz"

show_excerpts: true

github_username: HVboom
